### ISSUE TITLE
Add hover on 'my location' symbol

### ISSUE THREAD

**Issue by adhityapy** [petabencana/riskmap#18]
Add hover information on 'my location' symbol on the map, to help user identify symbols.

![ss gmap](https://user-images.githubusercontent.com/61488978/75323381-5b22a000-58a7-11ea-9c48-aae17bce31f8.jpg)

![image](https://user-images.githubusercontent.com/34257163/126430354-10886bd8-8d2c-4eec-b990-9aefee20a629.png)

show on hover -> BI : 'Tampilkan lokasi saya'
                            EN : 'Show my location'

note: this feature might only be applied on desktop UI

**Comment by Deepthi-Chand** [comment]
This content is controlled my the map. Will check if it is possible for us to plug into it and change

**Comment by anaritawidya** [comment]
@Deepthi-Chand 
I have checked on it and still not updated yet, the logic is the same with the report button (see below)
![image](https://user-images.githubusercontent.com/34257163/111588792-9798a500-87f6-11eb-8ac7-4e90bde87629.png)
this issue is not really a priority, but if it's not really major and you are able to fix that along with the interface update, that would be great.

**Comment by anaritawidya** [comment]
not seeing the change, can you please check again @Deepthi-Chand

**Comment by anaritawidya** [comment]
havent seen the change
